### ISSUE TITLE
Full Node Crashes with Different Proposer Address on Contract Deployment

### ISSUE THREAD

**Issue by khalifaT** [artela-network/artela-rollkit#17]
# Description
When deploying a contract to a full node synced with our sequencer, the node crashes with a panic. While simple transfer transactions work fine, contract deployment fails with an error indicating the validator does not exist for a particular consensus address.
**Error Message**
```failed to ApplyBlock: proposal processing resulted in an invalid application state
goroutine 361 [running]: github.com/rollkit/rollkit/block.(*Manager).trySyncNextBlock(0xc001367800, {0x935a710, 0xc0028a0500}, 0x51c691)
/home/root/go/pkg/mod/github.com/rollkit/rollkit@v0.13.10/block/manager.go:548 +0x81c
ERR Transaction verification failed error="failed to get evm config from context: failed to obtain coinbase address: failed to retrieve validator from block proposer address artvalcons1cmgs93cgwmhpzwdyvw80zm4av20jdrvgh9lz8f: validator does not exist [artela-rollkit/x/evm/keeper/proposer.go:16]" module=server
```
**Investigation**
I've added logging to print the proposerAddress inside the EVM config.
The issue appears in:

* https://github.com/artela-network/artela-rollkit/blob/a2e9af5ea6d2890f8b3f4f8de1329e21bb672db3/app/ante/evm/aspect_context.go#L56
* https://github.com/artela-network/artela-rollkit/blob/a2e9af5ea6d2890f8b3f4f8de1329e21bb672db3/x/evm/keeper/config.go#L29

**Key Finding**
 Most log messages show the correct sequencer address, matching the sequencer logs. However, the last message shows a different validator address, which causes the error.
**Hypothesis**
The GetProposerAddress function in the code takes a parameter (proposerAddress) but should potentially be retrieving the consensus address . For some reason, during contract deployment, the function is being called with an incorrect validator address that doesn't exist in the registry.

## Reproduction Steps

* Deploy a full node with the sequencer
* Sync the node (transfer transactions work fine)
* Attempt to deploy a contract
* Node crashes with the validator error

**Comment by lukeweb3** [comment]
​I attempted to deploy a contract via a full node and did not encounter any node crashes. Please let me know if there are any differences in our reproduction steps.

Here are the steps I followed to reproduce the process:​

1. Start the sequencer using the attached **Docker Compose configuration**.
2. Launch a full node on the local network without the `--rollkit.aggregator` flag, and set the seed to the sequencer node.​
3. Connect MetaMask wallet to the full node's JSON-RPC port (`8545`).​
4. Deploy the `1_Storage.sol `contract to the full node via [Remix Ethereum](https://remix.ethereum.org/) using the "Injected Provider - MetaMask" option.​

Review the deployment logs as shown below; everything appears to be normal:

![Image](https://github.com/user-attachments/assets/802593ef-3c74-4e5a-be11-b9b720350b67)

**Docker Compose configuration**:
```yaml
# Docker Compose is used for spinning up the local-da docker container along with the GM container.

version: "3.8"
services:
  artroll:
    container_name: artroll
    # The build config can be used for debugging and testing changes to the Dockerfile
    # build: .

    # The image config can be used for running against published images
    image: artelanetwork/rollkit:latest

    # Used for targetting localhost as if you were outside the container
    ports:
      - "26656:26656"

    # Always pull the latest image
    pull_policy: always

    # The command config is used for launching the GM rollup once the Docker container is running
    command: rollkit start --rollkit.aggregator --rollkit.da_address http://local-da:7980
    depends_on:
      - local-da
    networks:
      - art_net

  local-da:
    image: ghcr.io/rollkit/local-da:v0.2.1
    container_name: local-da
    ports:
      - "7980:7980"
    networks:
      - art_net

networks:
  art_net:
    driver: bridge
```
